### ISSUE TITLE
Do not show hidden profiles

### ISSUE THREAD

**Issue by guntern** [paradox00/Flow.Launcher.Plugin.WindowsTerminal#2]
Thank you very much for this plugin. After reading, that the powertoys launcher had this included, I was longing for a solution in flow launcher. Actually I would prefer powertoys to be based on flow launcher instead of wox, but that's a different story.

I was irritated, that also my hidden terminal profiles show up in the query results. I would like to omit them there. I tried a quick hack in the pluging, but failed. In the end I thought it would maybe be nice if there was an option where the users could select, whether hidden profiles should be shown or not.

Best regards,
Gunter

edit: I played a little more with the terminal_profiles_test.py. I found that the hidden property of all the profiles in the list appears to be "True" regardless of the actual entry in the settings.json of Windows Terminal. So my naive code in the query method has worked (I got no more results), but the input data was not correct. I dig a little further.

edit2: I may have found an issue, when parsing the profiles - at least for python 3.10. I am not sure for other python versions. See : https://github.com/paradox00/Flow.Launcher.Plugin.WindowsTerminal/pull/3. But this is not the heart of this issue anymore, because a proper solution with a setting would be preferred in my point of view.

**Comment by paradox00** [comment]
Thanks for you warm words :)

I'll add setting option do show hide hidden profiles.

**Comment by guntern** [comment]
Thank you very much for adding the feature. I already was thinking of trying to implement it on my own. Your pluging is actually a good starting point for me to get into the programming of flow launcher plugins :-) How does the update finally end up in my installation? Currently only the 0.0.7 is listed in the various places.

**Comment by taooceros** [comment]
> Thank you very much for adding the feature. I already was thinking of trying to implement it on my own. Your pluging is actually a good starting point for me to get into the programming of flow launcher plugins :-) How does the update finally end up in my installation? Currently only the 0.0.7 is listed in the various places.

We need to wait a while for flow's plugin manifest's CI to trace the update (which is run every 3 hours). They should be available now :)

**Comment by guntern** [comment]
> > Thank you very much for adding the feature. I already was thinking of trying to implement it on my own. Your pluging is actually a good starting point for me to get into the programming of flow launcher plugins :-) How does the update finally end up in my installation? Currently only the 0.0.7 is listed in the various places.
> 
> We need to wait a while for flow's plugin manifest's CI to trace the update (which is run every 3 hours). They should be available now :)

We really have to wait a long time. The flow launcher web site now lists 0.0.8 as version. But calling `pm update` still claims that there are no updates for the plugins.

**Comment by taooceros** [comment]
Yeah you need to manually refresh the manifest info by typing refresh in the plugin store in setting panel. In the future, it will fetch the manifest in the real time.

**Comment by guntern** [comment]
ah thanks. I will try that next time. I thought it might have been an issue
when fiddling around with the files for testing. So I uninstalled and
reinstalled. Now I have it working like a charme :-)

Am Di., 18. Jan. 2022 um 21:29 Uhr schrieb Kevin Zhang <
***@***.***>:
